version: '3'
services:
  smb-server:
    build: ./server
    container_name: smb-server
    networks:
      - samba-test
  smb-client:
    build: ./client
    container_name: smb-client
    networks:
      - samba-test
  
networks:
  samba-test:
